/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  alarm_history: () => import("@/views/alarm/history/index.vue"),
  alarm_realtime: () => import("@/views/alarm/realtime/index.vue"),
  alarm_rule: () => import("@/views/alarm/rule/index.vue"),
  collection_node: () => import("@/views/collection/node/index.vue"),
  collection_task: () => import("@/views/collection/task/index.vue"),
  device_label: () => import("@/views/device/label/index.vue"),
  device_list: () => import("@/views/device/list/index.vue"),
  device_protocol: () => import("@/views/device/protocol/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  monitor_historical: () => import("@/views/monitor/historical/index.vue"),
  monitor_realtime: () => import("@/views/monitor/realtime/index.vue"),
  monitor_statistics: () => import("@/views/monitor/statistics/index.vue"),
};
