version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
  influxdb:
    image: influxdb:2
    ports: ["8086:8086"]
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: devorg
      DOCKER_INFLUXDB_INIT_BUCKET: collected
      DOCKER_INFLUXDB_INIT_RETENTION: 30d
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: devdcp-token
    volumes:
      - influxdb_data:/var/lib/influxdb
  redis:
    image: redis:7
  query-api:
    build: ../platform/center/Query.Api
  auth-api:
    build: ../platform/center/Auth.Api
  admin-api:
    build: ../platform/center/Admin.Api
    ports: ["18083:8080"]
  gateway-api:
    build: ../platform/center/Gateway.Api
    ports: ["18020:8080"]
    volumes:
      - ./logs/gateway:/app/logs
  monitor-api:
    build: ../platform/center/Monitor.Api
  processor-worker:
    build: ../platform/center/Processor.Worker
  scheduler-worker:
    build: ../platform/center/Scheduler.Worker

volumes:
  influxdb_data:
